### ISSUE TITLE
Why was @vue-storefront/eslint-config archived?

### ISSUE THREAD

**Issue by Tofandel** [vuestorefront/storefront-nuxt3-boilerplate#194]
### Describe the feature

The https://github.com/vuestorefront/eslint-config repo has been archived, what's up with that, what's the alternative?
The boilerplate is still using it

### Additional information

- [ ] Would you be willing to help implement this feature?
- [ ] Could this feature be implemented as a module?

### Final checks

- [X] Read the [contribution guide](https://github.com/vuestorefront/.github/blob/main/CONTRIBUTING.md).
- [X] Check existing discussions and issues.

**Comment by FRSgit** [comment]
Hey @Tofandel!

`@vue-storefront/eslint-config` source code has been moved to a [new monorepo](https://github.com/vuestorefront/vue-storefront/tree/main/engineering-toolkit/eslint-config). You can notice that change in the "homepage" section of the [NPM package page](https://www.npmjs.com/package/@vue-storefront/eslint-config).

Hope that helps!
